
const BaseDeDatosProductos = {
    1001: {
        nombre: "Balón adidas Fútbol Mundial Fifa 26 Trionda League Jd8030",
        categoria: "Futbol",
        marca: "Adidas",
        precio: "$139.990",
        precioOriginal: "$199.900",
        descripcion: "Balón oficial con certificación FIFA Quality, diseñado para brindar máxima precisión y durabilidad. Ideal tanto para entrenamientos intensos como para competencias profesionales.",
        imagen: "Img/Catalogo/1001.png",
        detalle1: "Preciso al patear.",
        detalle2: "Duradero.",
        detalle3: "Apto para entrenamientos y partidos.",
        detalle4: "Certificado FIFA.",
        id: "1001"
    },
    1002: {
        nombre: "Camiseta Local Selección Colombia 24 Ip8279 aidas",
        categoria: "Camisetas-deportivas",
        marca: "Adidas",
        precio: "$209.900",
        precioOriginal: "",
        descripcion: "Camiseta oficial de la Selección Colombia 2024, fabricada con materiales transpirables y cómodos. Su diseño moderno y liviano permite libertad de movimiento y muestra el orgullo nacional.",
        imagen: "Img/Catalogo/1002.png",
        detalle1: "Material ligero.",
        detalle2: "Cómoda al moverse.",
        detalle3: "Permite transpirar.",
        detalle4: "Diseño moderno.",
        id: "1002"
    },
    1003: {
        nombre: "Guantes Arquero Competencia Golty Titan Keeper Negro/verde Color Negro Talla 8",
        categoria: "Futbol",
        marca: "Golty",
        precio: "$249.900",
        precioOriginal: "",
        descripcion: "Guantes de arquero con gran agarre y protección, fabricados con palma de látex y refuerzos resistentes. Perfectos para partidos exigentes o entrenamientos de alto nivel.",
        imagen: "Img/Catalogo/1003.png",
        detalle1: "Buen agarre.",
        detalle2: "Protege las manos.",
        detalle3: "Reforzados y duraderos.",
        detalle4: "",
        id: "1003"
    },
    1004: {
        nombre: "Raqueta Head Tour Pro 4 3/8 Nano Titanium Xtr P Color Negro",
        categoria: "Tenis",
        marca: "Head",
        precio: "$229.900",
        precioOriginal: "",
        descripcion: "Raqueta equilibrada y ligera que combina potencia y control. Su estructura de nano titanio ofrece mayor estabilidad y una respuesta sólida en cada golpe.",
        imagen: "Img/Catalogo/1004.png",
        detalle1: "Ligera.",
        detalle2: "Potencia controlada.",
        detalle3: "Golpes precisos.",
        detalle4: "",
        id: "1004"
    },
    1005: {
        nombre: "Rodilleras Deporte Miyagi Voleibol Patinaje Basket Multiusos",
        categoria: "Voleibol",
        marca: "Miyagi",
        precio: "$50.915",
        precioOriginal: "$59.900",
        descripcion: "Rodilleras acolchadas con diseño ergonómico que protegen las articulaciones y brindan confort. Ideales para voleibol, patinaje, baloncesto o cualquier deporte de impacto.",
        imagen: "Img/Catalogo/1005.png",
        detalle1: "Protege rodillas.",
        detalle2: "Cómodas.",
        detalle3: "Diseño ergonómico.",
        detalle4: "Para deportes de impacto.",
        id: "1005"
    },
    1006: {
        nombre: "Balon Voleibol Molten V5m5000 Flistatec Original",
        categoria: "Voleibol",
        marca: "Molten",
        precio: "$258.930",
        precioOriginal: "$369.900",
        descripcion: "Balón profesional con tecnología Flistatec para una trayectoria más estable y controlada. Su superficie suave y resistente garantiza un excelente rendimiento en partidos y torneos.",
        imagen: "Img/Catalogo/1006.png",
        detalle1: "Vuelo estable.",
        detalle2: "Superficie resistente.",
        detalle3: "Ideal para torneos.",
        detalle4: "Control en cada golpe.",
        id: "1006"
    },
    1007: {
        nombre: "Tula Deportiva Industry Bag Maleta De Viaje Maletin Gimnasio",
        categoria: "Gimnasio",
        marca: "Industry Bag",
        precio: "$65.900",
        precioOriginal: "",
        descripcion: "Maleta amplia, resistente y ligera con múltiples compartimientos. Ideal para llevar ropa, calzado y accesorios deportivos, o incluso para viajes cortos.",
        imagen: "Img/Catalogo/1007.png",
        detalle1: "Mucho espacio.",
        detalle2: "Resistente y ligera.",
        detalle3: "Varias secciones para organizar.",
        detalle4: "",
        id: "1007"
    },
    1008: {
        nombre: "Termo Cubitt Tumbler 1100 Ml Color Obsidian",
        categoria: "Gimnasio",
        marca: "Cubbit",
        precio: "$129.900",
        precioOriginal: "",
        descripcion: "Termo de acero inoxidable con gran capacidad y diseño elegante. Mantiene bebidas frías o calientes por varias horas y es perfecto para uso diario o actividades al aire libre.",
        imagen: "Img/Catalogo/1008.png",
        detalle1: "Mantiene temperatura.",
        detalle2: "Gran capacidad.",
        detalle3: "Acero inoxidable.",
        detalle4: "Ideal para exteriores.",
        id: "1008"
    },
    1009: {
        nombre: "Tienda de campaña camuflada para 6 personas, resistente, color verde, camuflada",
        categoria: "CargueYTransporte",
        marca: "CampPro",
        precio: "$399.900",
        precioOriginal: "",
        descripcion: "Tienda espaciosa y resistente con diseño camuflado, ideal para campamentos familiares. Ofrece buena ventilación y protección contra la lluvia, el sol y el viento.",
        imagen: "Img/Catalogo/1009.png",
        detalle1: "Resistente al clima.",
        detalle2: "Espaciosa.",
        detalle3: "Buena ventilación.",
        detalle4: "Fácil de armar.",
        id: "1009"
    },
    1010: {
        nombre: "Balón Baloncesto Wilson Drive Basketball Nba Color Ocre #07",
        categoria: "Baloncesto",
        marca: "Wilson",
        precio: "$139.900",
        precioOriginal: "",
        descripcion: "Balón oficial con textura de alto agarre que ofrece un control excepcional. Diseñado para durar, es perfecto tanto para canchas interiores como exteriores.",
        imagen: "Img/Catalogo/1010.png",
        detalle1: "Buen agarre.",
        detalle2: "Durable.",
        detalle3: "Para interior y exterior.",
        detalle4: "Textura antideslizante.",
        id: "1010"
    },
    1011: {
        nombre: "Kit De Pesas Y Mancuernas Ajustables Set 12 Pz 20 Kg Negro",
        categoria: "Gimnasio",
        marca: "ProFit",
        precio: "$349.900",
        precioOriginal: "",
        descripcion: "Set completo de mancuernas ajustables con discos de peso intercambiables. Ideal para entrenar fuerza, tonificar músculos y personalizar tus rutinas en casa.",
        imagen: "Img/Catalogo/1011.png",
        detalle1: "Peso ajustable.",
        detalle2: "Entrena fuerza y tonifica.",
        detalle3: "Discos intercambiables.",
        detalle4: "Ideal para casa.",
        id: "1011"
    },
    1012: {
        nombre: "Plataforma de step Sportfitness 070204 Color Gris",
        categoria: "Gimnasio",
        marca: "Sportfitness",
        precio: "$89.910",
        precioOriginal: "$99.900",
        descripcion: "Plataforma resistente y antideslizante con altura ajustable. Perfecta para entrenamientos de step, cardio, tonificación y ejercicios de bajo impacto.",
        imagen: "Img/Catalogo/1012.png",
        detalle1: "Antideslizante.",
        detalle2: "Altura ajustable.",
        detalle3: "Resistente.",
        detalle4: "Para step y cardio.",
        id: "1012"
    },
    1013: {
        nombre: "Máquina Abdominales Ab Slimmer Sportiva Ejercicio Core Gym Color Azul",
        categoria: "Gimnasio",
        marca: "Sportiva",
        precio: "$119.500",
        precioOriginal: "",
        descripcion: "Una máquina de entrenamiento diseñada para trabajar los músculos del abdomen (superior e inferior), ideal para uso doméstico o gimnasio liviano. Su estructura en hierro, junto a agarres acolchados y soporte para la cabeza, permiten un entrenamiento cómodo, seguro y enfocado en tonificar la zona media del cuerpo.",
        imagen: "Img/Catalogo/1013.png",
        detalle1: "Base antideslizante para mayor estabilidad.",
        detalle2: "Soporte acolchado que protege cuello y espalda.",
        detalle3: "Estructura de acero resistente y duradera.",
        detalle4: "Ideal para fortalecer el abdomen y el core.",
        id: "1013"
    },
    1014: {
        nombre: "Zapatilla Turf Golty New Bio Flex Lykni Sintetica Sport",
        categoria: "Futbol",
        marca: "Golty",
        precio: "$161.910",
        precioOriginal: "$179.900",
        descripcion: "Zapatillas Golty New Bio Flex Lykni diseñadas para canchas de césped sintético. Fabricadas en material sintético resistente con tecnología Lyknit para un ajuste cómodo y suela con excelente agarre y estabilidad.",
        imagen: "Img/Catalogo/1014.png",
        detalle1: "Exterior sintético resistente ideal para superficies sintéticas.",
        detalle2: "Tecnología Lyknit que brinda ajuste tipo calcetín para mayor comodidad.",
        detalle3: "Suela optimizada para canchas turf o césped sintético con excelente agarre.",
        detalle4: "Diseño de rendimiento ligero que favorece la velocidad y estabilidad en el juego.",
        id: "1014"
    },
    1015: {
        nombre: "Canillera Espinillera Futbol Pro Protección En Pvc Sport",
        categoria: "Futbol",
        marca: "Sport",
        precio: "$21.600",
        precioOriginal: "$24.000",
        descripcion: "Protege tus espinillas durante el juego con esta espinillera “Futbol Pro” de Sport. Fabricada con carcasa rígida de PVC para absorber los impactos, ideal para entrenamientos y partidos en césped o sintético. Disponible en tallas para niños y jóvenes con cinturón o banda ajustable.",
        imagen: "Img/Catalogo/1015.png",
        detalle1: "Carcasa rígida de PVC que ofrece protección contra impactos.",
        detalle2: "Diseño liviano para no entorpecer el movimiento durante el juego.",
        detalle3: "Banda de sujeción o cinturón que mantiene la espinillera en posición.",
        detalle4: "Disponible en varias tallas y colores para adaptación juvenil/adulto.",
        id: "1015"
    },
    1016:{
        nombre: "Medias Antideslizantes Futbol Negras Amarillas Blancas",
        categoria: "Futbol",
        marca: "Atenas",
        precio: "$13.113",
        precioOriginal: "$27.900",
        descripcion: "Descripción breve: Medias antideslizantes pensadas para fútbol, diseñadas con una planta de goma que evita movimientos no deseados dentro del calzado, y tela transpirable que mantiene el pie seco durante el entrenamiento o partido.",
        imagen: "Img/Catalogo/1016.png",
        detalle1: "Planta de goma antideslizantes para mejor agarre.",
        detalle2: "Tejido transpirable y secado rápido para comodidad.",
        detalle3: "Soporte elástico reforzado para mayor estabilidad.",
        detalle4: "Costuras que evitan rozaduras y mejoran la durabilidad.",
        id: "1016"
    },
    1017: {
        nombre: "Balón De Fútbol Competencia Golty Fénix No.5 Blanco",
        categoria: "Futbol",
        marca: "Golty",
        precio: "$79.525",
        precioOriginal: "$109.000",
        descripcion: "Balón de fútbol diseñado para competición con tamaño oficial No. 5. Presenta tecnología Thermobonded y construcción sin costuras para ofrecer control, durabilidad y resistencia al agua. Ideal para uso en césped natural, sintético, tierra o arenilla.",
        imagen: "Img/Catalogo/1017.png",
        detalle1: "Cubierta en cuero PU de 4 mm de grosor con backing para mayor suavidad al toque.",
        detalle2: "Construcción termosellada sin costuras (Technología Thermobonded) que mejora la impermeabilidad y precisión.",
        detalle3: "Neumático con envoltura de hilo y rebote entre 110-135 cm que garantiza consistencia en cada golpe.",
        detalle4: "Tamaño oficial (circunferencia de 68-70 cm, peso 410-450 g) para adultos en #5, apto para múltiples superficies.",
        id: "1017"
    },
    1018: {
        nombre: "Manga De Protección Para Voleibol Voley Par Confirmar Unica",
        categoria: "Voleibol",
        marca: "Genérica/sin marca destacada.",
        precio: "$35.900",
        precioOriginal: "",
        descripcion: "Par de mangas protectoras para brazos pensadas para el voleibol; confeccionadas en materiales elásticos que se ajustan al brazo, con acolchado estratégico para absorber impactos y proteger antebrazos y muñeca. Ideal para entrenamientos o partidos.",
        imagen: "Img/Catalogo/1018.png",
        detalle1: "Tejido elástico (nylon/spandex) que garantiza ajuste cómodo al brazo.",
        detalle2: "Acolchado o espuma integrada para absorción de impactos al realizar pases o recibir la pelota.",
        detalle3: "Tira antideslizante interna que evita que la manga se desplace durante el juego.",
        detalle4: "Diseño transpirables y liviano para mantener confort durante entrenamientos largos.",
        id: "1018"
    },
    1019: {
        nombre: "Malla Red Voleibol Oficial Grosor #5 Con Guaya",
        categoria: "Voleibol",
        marca: "Genérica/Varios proveedores",
        precio: "$35.900",
        precioOriginal: "",
        descripcion: "Red de voleibol calibre #5 con guaya de acero, ideal para entrenamiento o partidos informales. Fabricada en nylon inmunizada y diseñada para uso interior o exterior, ofrece gran resistencia y durabilidad.",
        imagen: "Img/Catalogo/1019.png",
        detalle1: "Material de nylon calibre #5 para mayor resistencia.",
        detalle2: "Guaya de acero forrado que refuerza y mantiene la tensión.",
        detalle3: "Bordes reforzados con lona en los cuatro lados.",
        detalle4: "Medidas estándar reglamentarias para instalación en canchas.",
        id: "1019"
    },
    1020: {
        nombre: "Balon Voleibol Mikasa V200w Microfibra",
        categoria: "Voleibol",
        marca: "Mikasa",
        precio: "$399.990",
        precioOriginal: "",
        descripcion: "Balón de voleibol de competición oficial tamaño 5, con superficie de microfibra de doble hoyuelo («Double Dimple») que estabiliza la trayectoria y mejora el control. Diseño aerodinámico de 18 paneles para saltos, remates y pases precisos. Homologado por la FIVB para uso profesional.",
        imagen: "Img/Catalogo/1020.png",
        detalle1: "Superficie de microfibra + PU desarrollada en colaboración con Kuraray para tacto premium y durabilidad.",
        detalle2: "Diseño de 18 paneles perfectamente equilibrado para vuelo aerodinámico y control superior.",
        detalle3: "Tecnología antitranspiración ‘Nano Balloon Silica’ que evita que la superficie se vuelva resbaladiza durante el juego intenso.",
        detalle4: "Homologado para competencias FIVB: circunferencia 65-67 cm, peso 260-280 g, tamaño oficial 5.",
        id: "1020"
    },
    1021: {
        nombre: "Bolas De Tenis Wilson Tarro De Pelotas X3 Grand Slam Color Amarillo",
        categoria: "Tenis",
        marca: "Wilson",
        precio: "$22.690",
        precioOriginal: "$34.990",
        descripcion: "Tarro con 3 pelotas de tenis “Grand Slam”, ideales para uso recreativo o de entrenamiento. Con construcción extra duty que mejora la durabilidad en superficies duras.",
        imagen: "Img/Catalogo/1021.png",
        detalle1: "Construcción Extra Duty para mayor resistencia al desgaste en canchas duras.",
        detalle2: "Fieltro de alta calidad que mantiene el rebote y la consistencia del juego.",
        detalle3: "Presión estándar para ofrecer sensación de rendimiento equilibrado.",
        detalle4: "Formato en tarro de 3 unidades, práctico para entrenamientos o uso personal.",
        id: "1021"
    },
    1022: {
        nombre: "Red De Tenis De Fútbol Portátil",
        categoria: "Tenis",
        marca: "Genérica / modelo MSTP-SUMS4Genérica / modelo MSTP-SUMS4",
        precio: "$143.822",
        precioOriginal: "",
        descripcion: "Red portátil de fútbol-tenis de 4 metros de ancho, diseñada para prácticas, entrenamientos o juegos recreativos al aire libre. Incluye malla resistente, fácil de montar y transportar.",
        imagen: "Img/Catalogo/1022.png",
        detalle1: "Ancho de 4 m para cubrir espacio amplio de juego.",
        detalle2: "Malla de polietileno / nylon reforzado.",
        detalle3: "Diseño portátil: se arma y desarma con facilidad.",
        detalle4: "Incluye bolsa de transporte o sistema plegable.",
        id: "1022"
    },
    1023: {
        nombre: "Funda Forro Cubierta Enteriza Para Raqueta De Tennis",
        categoria: "Tenis",
        marca: "GrandSlam",
        precio: "$55.000",
        precioOriginal: "",
        descripcion: "Forro/cubierta enteriza diseñada para transportar y proteger una raqueta de tenis. Tiene cierre completo, correa para hombro, fabricada en nylon resistente o material similar, ideal para uso recreativo o de iniciación.",
        imagen: "Img/Catalogo/1023.png",
        detalle1: "Forro acolchado que protege la raqueta de golpes y arañazos.",
        detalle2: "Cierre de cremallera a lo largo para fácil acceso a la raqueta.",
        detalle3: "Correa ajustable para transporte cómodo al hombro.",
        detalle4: "Material resistente apto para uso cotidiano.",
        id: "1023"
    },
    1024:{
        nombre: "Banda Para La Cabeza adidas Tenis Unisex Negro Ht3909",
        categoria: "Tenis",
        marca: "Adidas",
        precio: "$33.202",
        precioOriginal: "$34.950",
        descripcion: "Banda para la cabeza de tenis diseñada para mantener el sudor fuera de los ojos en la cancha. Fabricada con materiales suaves y elásticos para ofrecer comodidad durante el juego, aporta estilo y funcionalidad.",
        imagen: "Img/Catalogo/1024.png",
        detalle1: "Talla única, se adapta a la mayoría de cabezas.",
        detalle2: "74 % poliéster reciclado, 23 % algodón, 3 % elastano.",
        detalle3: "Diseño absorbente y elástico.",
        detalle4: "",
        id: "1024"
    },
    1025: {
        nombre: "Aro Profesional Baloncesto Cesta Basketball Metal + Malla",
        categoria: "Baloncesto",
        marca: "Genérica/Basketballring",
        precio: "$105.900",
        precioOriginal: "",
        descripcion: "Aro de baloncesto profesional de 45 cm de diámetro, fabricado en metal con pintura electrostática para resistencia en exteriores e interiores. Incluye malla de nylon de calibre 5, preparado para montaje en pared o tablero, ideal para lugares de entrenamiento, patio o club.",
        imagen: "Img/Catalogo/1025.png",
        detalle1: "Diámetro estándar de 45 cm.",
        detalle2: "Construcción metálica robusta con pintura electrostática.",
        detalle3: "Incluye malla de nylon calibre 5.",
        detalle4: "11 ganchos de fijación para asegurar la malla al aro.",
        id: "1025"
    },
    1026:{
        nombre: "Tablero De Baloncesto En Acrílico 90cm X 120cm",
        categoria: "Baloncesto",
        marca: "Genérica / Fabricante especializado en acrílico",
        precio: "$215.355",
        precioOriginal: "$310.900",
        descripcion: "Tablero de baloncesto fabricado en lámina de acrílico transparente de 10 mm de grosor, con dimensiones de 90 cm × 120 cm. Ideal para instalación en interior o exteriores, soporta impacto, ofrece buena visibilidad y una estética moderna para canchas deportivas residenciales o comunitarias.",
        imagen: "Img/Catalogo/1026.png",
        detalle1: "Material de acrílico cristal de 10 mm de grosor.",
        detalle2: "Medida estándar 90 cm x 120 cm.",
        detalle3: "Líneas demarcatorias reglamentarias incluidas en el tablero.",
        detalle4: "Adecuado tanto para uso en interiores como exteriores.",
        id: "1026"
    },
    1027: {
        nombre: "Zapatillas De Baloncesto De Caña Alta Para Hombre",
        categoria: "Baloncesto",
        marca: "adidas",
        precio: "$128.482",
        precioOriginal: "$136.269",
        descripcion: "Zapatilla de baloncesto de corte alto diseñada para alto rendimiento. Proporciona excelente soporte al tobillo gracias a su caña alta, materiales premium y tecnología dedicada a jugar con comodidad, control y estilo en la cancha.",
        imagen: "Img/Catalogo/1027.png",
        detalle1: "Corte alto para máximo soporte del tobillo.",
        detalle2: "Mediasuela amortiguada que absorbe impactos y favorece en cada salto.",
        detalle3: "Suela de goma con patrón multidireccional para tracción óptima.",
        detalle4: "Materiales premium en el empeine.",
        id: "1027"
    },
    1028: {
        nombre: "1 Par De Calcetines De Baloncesto Antideslizantes Para Depor",
        categoria: "Baloncesto",
        marca: "Marca genérica",
        precio: "$12.722",
        precioOriginal: "$18.670",
        descripcion: "Par de calcetines antideslizantes diseñados para baloncesto o deportes de equipo. La suela incorpora almohadillas o silicona antideslizante que mejora la tracción dentro del zapato, mientras que la tela transpirable mantiene el pie seco durante el juego.",
        imagen: "Img/Catalogo/1028.png",
        detalle1: "Almohadillas de silicona antideslizante en la planta.",
        detalle2: "Tejido transpirable de malla en empeine.",
        detalle3: "Talón y puntera reforzados para mayor durabilidad en entrenamientos.",
        detalle4: "Diseño unisex-adulto.",
        id: "1028"
    },
    1029: {
        nombre: "Saco De Dormir Sleeping Bag Ecology Trekker Bolsa De Dormir Color Azul Marino",
        categoria: "CargueYTransporte",
        marca: "Ecology Trekker",
        precio: "$79.990",
        precioOriginal: "$147.990",
        descripcion: "Saco de dormir térmico ideal para campamentos, excursiones o viajes al aire libre. Fabricado con materiales ligeros y aislantes que conservan el calor corporal, ofreciendo comodidad incluso en noches frías. Su diseño compacto y cierre lateral izquierdo facilitan el uso y transporte, siendo perfecto para climas templados y fríos.",
        imagen: "Img/Catalogo/1029.png",
        detalle1: "Relleno sintético de fibra hueca siliconada.",
        detalle2: "Cubierta exterior impermeable que protege contra la humedad.",
        detalle3: "Cierre lateral izquierdo con cremallera de doble vía.",
        detalle4: "Incluye funda compacta con correas para transporte.",
        id: "1029"
    },
    1030: {
        nombre: "Mochila Táctica Militar Outdoor Pentagon 30L Impermeable",
        categoria: "CargueYTransporte",
        marca: "Pentagon",
        precio: "$87.000",
        precioOriginal: "$119.990",
        descripcion: "Mochila táctica de 30 litros diseñada para actividades al aire libre, senderismo, campamentos o uso urbano. Fabricada con materiales resistentes al agua y múltiples compartimientos para una organización eficiente. Su estructura ergonómica garantiza comodidad y durabilidad incluso en condiciones extremas.",
        imagen: "Img/Catalogo/1030.png",
        detalle1: "Capacidad de 30L con múltiples bolsillos y compartimientos internos.",
        detalle2: "Material impermeable y resistente al desgaste.",
        detalle3: "Correas acolchadas y ajustables para hombros y pecho.",
        detalle4: "Sistema MOLLE para añadir accesorios adicionales.",
        id: "1030"
    },
    1031: {
        nombre: "Kit De Supervivencia Sos Caja Herramientas Multiusos Camping",
        categoria: "CargueYTransporte",
        marca: "SOS Survival",
        precio: "$58.900",
        precioOriginal: "",
        descripcion: "Completo kit de supervivencia compacto ideal para camping, senderismo o emergencias. Incluye herramientas esenciales como navaja, linterna, silbato, brújula y pedernal, todo dentro de una caja resistente al agua. Diseñado para brindar seguridad y preparación en cualquier entorno al aire libre.",
        imagen: "Img/Catalogo/1031.png",
        detalle1: "Incluye navaja táctica, linterna LED, silbato, brújula y pedernal.",
        detalle2: "Estuche compacto, impermeable y resistente a golpes.",
        detalle3: "Ideal para campamentos, excursiones, rescates o supervivencia urbana.",
        detalle4: "Ligero y fácil de transportar.",
        id: "1031"
    },
    1032: {
        nombre: "Hielera 16 Qt Latitude Azul Indigo 24 Latas Igloo",
        categoria: "CargueYTransporte",
        marca: "Igloo",
        precio: "$260.899",
        precioOriginal: "$299.900",
        descripcion: "Hielera portátil de 16 cuartos (15 L) ideal para mantener tus bebidas y alimentos fríos durante paseos, campamentos o días de playa. Su diseño resistente y práctico ofrece un rendimiento duradero, con aislamiento térmico de alta eficiencia y capacidad para hasta 24 latas.",
        imagen: "Img/Catalogo/1032.png",
        detalle1: "Capacidad de 16 Qt (15 L), hasta 24 latas.",
        detalle2: "Aislamiento térmico de alta densidad para mantener el frío.",
        detalle3: "Asa ergonómica para transporte cómodo y seguro.",
        detalle4: "Fabricada en plástico duradero con diseño azul resistente a impactos.",
        id: "1032"
    },
    1033: {
        nombre: "Pack X3 Camisetas Deportivas Originales Top Quality Oppen",
        categoria: "Camisetas-deportivas",
        marca: "Ripple",
        precio: "$120.768",
        precioOriginal: "$188.700",
        descripcion: "Set de tres camisetas deportivas de alto rendimiento elaboradas con materiales transpirables y ligeros. Ideales para entrenamiento, gimnasio o actividades al aire libre, ofreciendo comodidad, elasticidad y libertad de movimiento.",
        imagen: "Img/Catalogo/1033.png",
        detalle1: "Tela transpirable de secado rápido.",
        detalle2: "Corte ergonómico para mayor movilidad.",
        detalle3: "Costuras reforzadas para durabilidad.",
        detalle4: "Ideal para running, gym o uso diario.",
        id: "1033"
    },
    1034: {
        nombre: "Camiseta Hombre Original Manga Sisa Deportiva Ripple",
        categoria: "Camisetas-deportivas",
        marca: "Ripple",
        precio: "$44.469",
        precioOriginal: "$54.900",
        descripcion: "Camiseta Hombre Original Manga Sisa Deportiva Ripple",
        imagen: "Img/Catalogo/1034.png",
        detalle1: "Tela liviana y transpirable.",
        detalle2: "Diseño sin mangas para mayor movilidad.",
        detalle3: "Secado rápido y suave al tacto.",
        detalle4: "Ideal para gimnasio y actividades al aire libre.",
        id: "1034"
    },
    1035: {
        nombre: "M Sl Sj T Je9024 adidas",
        categoria: "Camisetas-deportivas",
        marca: "Adidas",
        precio: "$99.950",
        precioOriginal: "",
        descripcion: "Camiseta deportiva sin mangas Adidas M SL SJ T JE9024, diseñada para entrenamientos intensos. Ofrece una excelente ventilación, ligereza y comodidad, ideal para quienes buscan rendimiento y estilo en sus rutinas.",
        imagen: "Img/Catalogo/1035.png",
        detalle1: "Tecnología AEROREADY que absorbe la humedad.",
        detalle2: "Corte regular con cuello redondo.",
        detalle3: "Tela de poliéster reciclado suave y ligera.",
        detalle4: "Ideal para gimnasio, running o entrenamientos diarios.",
        id: "1035"
    },
    1036: {
        nombre: "Camiseta Manga Larga Lycra Jersey Deportivo Original Ripple",
        categoria: "Camisetas-deportivas",
        marca: "Ripple",
        precio: "$54.522",
        precioOriginal: "$69.900",
        descripcion: "Camiseta deportiva de manga larga confeccionada en lycra elástica y transpirable, ideal para entrenamientos, ciclismo o running. Brinda ajuste ceñido, comodidad y protección contra el sol y el sudor.",
        imagen: "Img/Catalogo/1036.png",
        detalle1: "Tela de lycra elástica y fresca.",
        detalle2: "Protección UV para exteriores.",
        detalle3: "Costuras planas que evitan rozaduras.",
        detalle4: "Ideal para ciclismo, gym y running.",
        id: "1036"
    },
    1037: {
        nombre: "Gafas De Natación Zoom X-fit Color Pink/Smoke/Black",
        categoria: "Natacion",
        marca: "Arena",
        precio: "$87.400",
        precioOriginal: "",
        descripcion: "Gafas de natación Zoom X-fit con diseño ergonómico y lentes ahumados que ofrecen protección UV y visión clara bajo el agua. Ideales para entrenamientos o competencias, garantizan comodidad y ajuste seguro.",
        imagen: "Img/Catalogo/1037.png",
        detalle1: "Lentes con protección UV y antiempañante.",
        detalle2: "Correa ajustable de silicona resistente.",
        detalle3: "Diseño ergonómico para mejor sellado.",
        detalle4: "Apta para uso recreativo o profesional.",
        id: "1037"
    },
    1038: {
        nombre: "Kit Paletas X2 Mano Natación 1 Par De Aletas Entrenamiento",
        categoria: "Natacion",
        marca: "SwimPro",
        precio: "$39.890",
        precioOriginal: "",
        descripcion: "Set de entrenamiento para natación que incluye un par de paletas de mano y un par de aletas de potencia. Diseñado para mejorar la fuerza, la técnica de brazada y la resistencia durante el entrenamiento acuático.",
        imagen: "Img/Catalogo/1038.png",
        detalle1: "Paletas ergonómicas para mejorar la técnica.",
        detalle2: "Aletas de silicona cómodas y duraderas.",
        detalle3: "Aumenta la resistencia y la velocidad.",
        detalle4: "Ideal para entrenamientos en piscina o mar.",
        id: "1038"
    },
    1039: {
        nombre: "Gorro Natación Buceo Piscina Wonder Silicona Entrenamiento",
        categoria: "Natacion",
        marca: "Wonder",
        precio: "$9.546",
        precioOriginal: "$12.900",
        descripcion: "Gorro de natación en silicona flexible y resistente, diseñado para proteger el cabello del cloro y mejorar la hidrodinámica en el agua. Ideal para entrenamientos, buceo o uso recreativo.",
        imagen: "Img/Catalogo/1039.png",
        detalle1: "Silicona suave y elástica de alta calidad.",
        detalle2: "Ajuste cómodo y anatómico.",
        detalle3: "Resistente al cloro y al deslizamiento.",
        detalle4: "Ideal para natación, buceo y piscina.",
        id: "1039"
    },
    1040: {
        nombre: "Aletas De Natación Para Nadar, Esnórquel, Aletas Cortas De B",
        categoria: "Natacion",
        marca: "Genérica",
        precio: "$181.187",
        precioOriginal: "",
        descripcion: "Aletas de natación diseñadas en silicona para uso en piscina, entrenamiento o esnórquel. Su pala corta favorece una frecuencia de patada alta, mejora la técnica y fortalece el tren inferior sin alterar la postura natural del nadador.",
        imagen: "Img/Catalogo/1040.png",
        detalle1: "Pala corta para patada rápida.",
        detalle2: "Calzante de silicona, ajuste seguro.",
        detalle3: "Material resistente al cloro y al uso.",
        detalle4: "Diseño técnico para entrenamiento eficiente.",
        id: "1040"
    },
    1041: {
        nombre: "Tapones Oídos + Clip De Nariz Natación Dormir Impermeables",
        categoria: "Natacion",
        marca: "Bestway",
        precio: "$19.350",
        precioOriginal: "$34.999",
        descripcion: "Juego económico que incluye pinza para la nariz y tapones para los oídos, ideales para nadar, entrenar o dormir sin que entre agua o sudor.",
        imagen: "Img/Catalogo/1041.png",
        detalle1: "Pinza nasal de silicona antideslizante.",
        detalle2: "Tapones oídos de silicona impermeables.",
        detalle3: "Incluye estuche compacto para transporte.",
        detalle4: "Uso multi-propósito: natación, ducha, dormir.",
        id: "1041"
    }
};